#!/bin/sh

# Mount necessary filesystems
mkdir -p /mnt/hostshare

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mount -t 9p -o trans=virtio hostshare /mnt/hostshare

# Add additional setup here, if necessary
echo "Welcome to the initramfs!"
/bin/sh

# Unmount filesystems before exiting
umount /proc
umount /sys
umount /dev

exit 0
